name: Swift

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: setup
      run: |
        curl -Ls https://install.tuist.io | bash
        rm -rf .package.resolved
        make generate
      
    - name: build
      run: tuist build
